spring.application.name=epc

# Primary database (default)
spring.datasource.url=jdbc:mysql://localhost:3306/epc?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Japan@123

# JPA for primary
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Secondary database
secondary.datasource.url=jdbc:mysql://another-server-ip:3306/secondary_db?useSSL=false&serverTimezone=UTC
secondary.datasource.username=secondary_user
secondary.datasource.password=secondary_password

spring.security.user.name=
spring.security.user.password=
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
